### ISSUE TITLE
gitbook 各种报错跑不起来。

### ISSUE THREAD

**Issue by zhayes** [whatot/leeao#1]
运行gitbook中间各种乱七八糟八糟的报错。
其中安装"betterchinese",这个插件报错。然后我把这个插件从book.json文件里删了。

但是最后运行 gitbook serve `的时候又报错`
```
error: error while parsing page "01.自传回忆类": 

Error: EISDIR: illegal operation on a directory, read
```
目前就卡在这了。
![image](https://user-images.githubusercontent.com/17758062/115171898-af659080-a0f6-11eb-8fa6-70729b05424d.png)

**Comment by whlshdw** [comment]
你好，删除 SUMMARY.md 文件中所有目录无 .md 文件的描述内容，即可运行成功。如: * [01.自传回忆类]~~(01.自传回忆类)~~ 
![image](https://user-images.githubusercontent.com/78549553/135567492-19270cd9-306a-40c8-b002-231704da729c.png)

**Comment by whatot** [comment]
最新的版本已经从gitbook迁移到mdbook，已经正常构建，并且markdown文件正在持续优化中。
