### ISSUE TITLE
一处错字

### ISSUE THREAD

**Issue by yunhao-qian** [whatot/leeao#3]
首先感谢这个仓库，实在是方便了检索文字！

刚才偶然发现，[此行](https://github.com/whatot/leeao/blob/0895354e3b2a814269e428b7c18a2815b7e796bc/06.%E6%B2%89%E6%80%9D%E6%97%A5%E8%AE%B0%E7%B1%BB/%E6%9D%8E%E6%95%96%E6%9C%AD%E8%AE%B0.md?plain=1#L571)的“木如靠老落”似乎为OCR识别错误，应是“不如靠老蒋”。

请问仓库主人方便接受错字订正么？以后若再偶然看到错字，我可以一并做个pull request。

**Comment by xiaoao19** [comment]
这个库太老了 有个新库 books.leeao.net
